services:
  nestjs_api:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - NODE_ENV=dev
      - MONGO_URI=mongodb://admin:1234@database:27017/restaurants
      - MONGO_NAME=restaurants
      - MONGO_USER=admin
      - MONGO_PASSWORD=1234
    volumes:
      - ./src:/usr/src/app/src

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_USER: root
      MONGO_PASSWORD: 12345
